### DISCUSSION TITLE
[Feature Request]: Option to deploy traefik in k3s's default namespace `kube-system`

### DISCUSSION THREAD

**Discussion by schlichtanders** [mysticaltech/terraform-hcloud-kube-hetzner#1042] [Ideas]
### Description

I am creating a local test environment via k3d (which probably almost everyone else would also prefer for a local test environment similar to kube-hetzner)

I was surprised finding that my traefik configuration mismatched between kube-hetzner and k3d, which seems to be because k3s by default deploys traefik into `kube-system` namespace.

Could we create an option to create traefik in this default namespace, or is there a particular preventing reason why the namespace was changed to `traefik` in kube-hetzner

**Comment by mysticaltech** [comment]
@schlichtanders Are you sure about this, normally kube-hetzner has traefik deployed on kube-system. See:

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/d80eb454c07bf98de2e1f98e5e4fbdc4c9594d51/templates/traefik_ingress.yaml.tpl#L11

**Comment by schlichtanders** [comment]
Hi @mysticaltech,

it seems that the namespace attribute of a helmchart kind does not really count - the `targetNamespace` is decisive.

https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/templates/traefik_ingress.yaml.tpl#L15
here the entire tpl file:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: traefik
  repo: https://traefik.github.io/charts
  targetNamespace: traefik
  bootstrap: true
  valuesContent: |-
    ${values}
```

**Comment by schlichtanders** [comment]
I guess the same request holds for nginx, which is currently deployed into its own nginx namespace instead of kube-system.

**Comment by mysticaltech** [comment]
@schlichtanders You are right, thanks for the info. Will do but it needs to be  backward compatible, so will add a `ingress_controller_use_system_namespace`  boolean variable to determine that.

**Comment by M4t7e** [comment]
@schlichtanders I'm not sure if we should take a development/test K8s setup as a reference for Kube Hetzner. All smaller K8s setups like k3d, kind, etc. do not have presets for production purposes, but just for simplicity and quick/easy deployment. You won't find many best practices there.

I'm not sure about the Traefik recommendations, but at least the K8s Ingress NGINX Controller should be installed in a dedicated namespace according to the docs. Technically, it doesn't matter in which namespace ingress controllers are installed, as they usually work across namespaces by default. The only reason to separate it (afaik) is for better RBAC management. See also here: https://kubernetes.github.io/ingress-nginx/deploy/rbac/

Btw, the default namespace for K8s Ingress NGINX Controller is `ingress-nginx` and not `nginx` as we use it today ^^

Regarding `metadata.namespace` vs. `spec.targetNamespace`, this is what the [documentation](https://docs.k3s.io/helm#using-the-helm-controller) says:
>Note that the HelmChart resource itself is in the **kube-system** namespace, but the chart's resources will be deployed to the **web** namespace, which is created in the same manifest

Example:
```yml
metadata:
  namespace: kube-system
spec:
  targetNamespace: web
```
