### DISCUSSION TITLE
examples how to setup ArgoCD

### DISCUSSION THREAD

**Discussion by Marek00Malik** [mysticaltech/terraform-hcloud-kube-hetzner#1068] [Q&A]
Hello guys, 

Could someone help with the argo cd setup, maybe some examples on how do you setup ArgoCD with Kustomize? 
I'm trying to use the example that is located on ArgoCD's website -> [link](https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#kustomize). 

But there are some issues that I'm not able to jump over. 

I'm running the following code as value for `extra_kustomize_deployment_commands` variable: 
```
  extra_kustomize_deployment_commands = <<-EOT
    kubectl -n argocd wait --for condition=established --timeout=120s crd/appprojects.argoproj.io
    kubectl -n argocd wait --for condition=established --timeout=120s crd/applications.argoproj.io
    kubectl apply -f /var/user_kustomize/argocd-application.yaml
  EOT
```

The argocd-application.yaml file is coming from `argocd-application.yaml.tpl`  > 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.2/manifests/install.yaml
```

I'm getting the following error: 
```
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): Connected!
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): Deploying manifests from /var/user_kustomize/:
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): total 12K
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): drwxr-xr-x. 1 root root 164 Oct 26 09:48 .
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): drwxr-xr-x. 1 root root 142 Oct 26 09:12 ..
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): -rw-r--r--. 1 root root 176 Oct 26 09:12 argo-application.yaml
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): -rw-r--r--. 1 root root 176 Oct 26 09:48 argocd-application.yaml
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): -rw-r--r--. 1 root root   0 Oct 26 09:48 argocd-projects.yaml
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): -rw-r--r--. 1 root root 103 Oct 26 11:53 kustomization.yaml
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): error: accumulating resources: accumulation err='accumulating resources from 'argocd-application.yaml': missing metadata.name in object {{kustomize.config.k8s.io/v1beta1 Kustomization} {{ } map[] map[]}}': must build at directory: '/var/user_kustomize/argocd-application.yaml': file is not directory
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): error: no objects passed to apply
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "appprojects.argoproj.io" not found
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "applications.argoproj.io" not found
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): error: resource mapping not found for name: "" namespace: "" from "/var/user_kustomize/argocd-application.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"
module.kube-hetzner.null_resource.kustomization_user_deploy[0] (remote-exec): ensure CRDs are installed first

```

**Comment by Marek00Malik** [comment]
Hi there. 
So, I've updated the `kustomization.yaml.tpl` file to contain what is recommended in the ArgoCD Deployment [example](https://github.com/argoproj/argoproj-deployments/blob/master/argocd/kustomization.yaml). 

I have the base & overlay files in the same location as kustomization.yaml.tpl file. 

```
├── extra-manifests
│   ├── base
│   │   ├── argo-cd-certificate.yaml
│   │   ├── argo-cd-issuer.yaml
│   │   ├── argo-cd-ui-ingress.yaml
│   │   ├── argocd-rbac-cm.yaml
│   │   └── rollouts-extension.yaml
│   ├── kustomization.yaml
│   ├── kustomization.yaml.tpl
│   └── overlays
│       └── production
│           ├── argo-cd-cm.yaml
│           ├── argocd-cmd-params-cm.yaml
│           ├── argocd-repo-server-deploy.yaml
│           └── argocd-server-service.yaml
```

These files from base and overlays are not moved to the container. 
I'm now getting the error that files from the base folder are missing. 
Can someone point me somewhere, what I'm missing?

**Reply by HendrikLevering** [reply]
I use argocd, but in a little bit different way. I deploy it with helm_release resource:

`resource "helm_release" "argocd" {
  name             = "argocd"
  repository       = "https://argoproj.github.io/argo-helm"
  chart            = "argo-cd"
  version          = "5.35.0" # Specify the version you want to install
  namespace        = "argocd"
  create_namespace = true
  set {
    name  = "redis-ha.enabled"
    value = "true" # Set the service type to LoadBalancer or NodePort as needed
  }

  set {
    name  = "controller.replicas"
    value = "1" 
  }
  set {
    name  = "server.replicas"
    value = "1" 
  set {
    name  = "repoServer.replicas"
    value = "2" 
  }
  set {
    name  = "applicationSet.replicas"
    value = "2" 
  }
}`

**Comment by nikolaszimmermann** [comment]
So, I introduced `extra_kustomize_deployment_commands` for exactly that setup: using ArgoCD.

I want to manage ArgoCD, using ArgoCD itself, and also "all applications" deployed on the cluster, exclusively.

That's how my deployment commands look like:

```
  # Extra commands to be executed after the `kubectl apply -k` (useful for post-install actions, e.g. wait for CRD, apply additional manifests, etc.).
  extra_kustomize_deployment_commands = <<-EOT
    kubectl apply -f /var/user_kustomize/certmanager-issuers.yaml

    kubectl -n argocd wait --for condition=established --timeout=120s crd/appprojects.argoproj.io
    kubectl -n argocd wait --for condition=established --timeout=120s crd/applications.argoproj.io
    kubectl apply -f /var/user_kustomize/argocd-projects.yaml
    kubectl apply -f /var/user_kustomize/argocd-application-argocd.yaml
    kubectl apply -f /var/user_kustomize/argocd-application-my-test-application.yaml
  EOT
```

The `argocd-*.yaml` files are generated from these:

```
./extra-manifests/argocd-projects.yaml.tpl
./extra-manifests/argocd-application-argocd.yaml.tpl
./extra-manifests/argocd-repositories.yaml.tpl
./extra-manifests/argocd-namespace.yaml
./extra-manifests/argocd-application-my-test-application.yaml.tpl
./extra-manifests/patches/argocd-cmd-params-cm.yaml
```

And here are dumps of the relevant files:

```
terraform/$ cat extra-manifests/patches/argocd-cmd-params-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: does-not-matter
data:
  # Run server without TLS
  server.insecure: "true"
```

(To disable TLS, encryption is handled by Traefik already)

```
terraform/$ cat ./extra-manifests/argocd-projects.yaml.tpl

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: ${your_project_name}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ${your_project_description}
  sourceRepos:
    - '*'
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
```

```
terraform/$ cat ./extra-manifests/argocd-application-argocd.yaml.tpl
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ${argocd_application_name}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${argocd_project_name}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: ${argocd_repository_url}
    targetRevision: ${argocd_repository_revision}
    path: ${argocd_repository_path}
    directory:
      recurse: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
```

```
terraform/$ cat ./extra-manifests/argocd-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
```

```
terraform/$ cat ./extra-manifests/argocd-repositories.yaml.tpl
apiVersion: v1
kind: Secret
metadata:
  name: ${your_repository_name}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${your_repository_url}
  username: ${your_repository_username}
  password: ${your_repository_password}
```
```
terraform/$ cat extra-manifests/kustomization.yaml.tpl
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ./argocd-namespace.yaml
- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=${argocd_repository_revision}
- ./argocd-repositories.yaml

patches:
- path: ./patches/argocd-cmd-params-cm.yaml
  target:
    name: argocd-cmd-params-cm
    kind: ConfigMap
```

And finally the values for the variables mentioned above:

```
  # Extra values that will be passed to the `extra-manifests/kustomization.yaml.tpl` if its present.
  extra_kustomize_parameters = {
    argocd_application_name    = "prod-argocd",
    argocd_project_name        = "default",
    argocd_repository_name     = "argo-cd.git",
    argocd_repository_path     = "manifests/cluster-install",
    argocd_repository_revision = "v2.9.0",
    argocd_repository_url      = "https://github.com/argoproj/argo-cd.git",
  
    your_image_registry      = "ghcr.io",
    your_image_repository    = "yourorg/yourproject",
    your_image_tag           = "some-tag",
    your_project_description = "Your desc",
    your_project_name        = "proj-name",
    your_repository_name     = "proj-name.git",
    your_repository_password = var.external_repository_password,
    your_repository_revision = "HEAD",
    your_repository_url      = "https://github.com/.../foobar.git",
    your_repository_username = "..."

...
  }
```

Probably some things are missing, I tried to strip down an actual production config for illustration purposes.
I sugest you to go that route, and avoid Helm. ArgoCD is all you need to manage the whole software :-) One can still deploy Helm apps via ArgoCD if needed.

Hope that helps.
