### DISCUSSION TITLE
basic auth for traefik dashboard

### DISCUSSION THREAD

**Discussion by thisIsLoading** [mysticaltech/terraform-hcloud-kube-hetzner#1116] [Q&A] [answered]
Hi,

i am pretty new to the whole k8s thing and found this repo through google (thank you for the awesome tool)

However, there is one thing that i just cant get to work, which is basic auth for the traefik dashboard. i am googling, reading and working on this for days now, but i just cant come up with a solution.

being a total newbie all kubernetes related doesnt help here either.

i have the following definitions:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: example-auth-secret
  namespace: traefik
type: kubernetes.io/basic-auth
data:
  username: dGVzdAo=
  password: dGVzdAo=

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: example-auth
  namespace: traefik
spec:
  basicAuth:
    removeHeader: true
    secret: example-auth-secret

---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
  namespace: traefik
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik-dashboard
spec:
  type: ClusterIP
  ports:
    - name: traefik
      port: 9000
      targetPort: traefik
      protocol: TCP
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: traefik-example-auth@kubernetescrd
spec:
  rules:
    - host: traefik-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard
                port:
                  number: 9000
  tls:
    - hosts:
        - traefik-staging.example.com
      secretName: traefik-staging-example-com
```

traefik is set up in the namespace `traefik`

without the `traefik-example-auth` enabled in the ingress, it loads the dashboard just fine, obviously without auth

user / pass are base64 encoded test / test. i have that verified directly via checking the secret.

however, the error i get is:

```
traefik-abcd-nd9tr traefik time="xxx" level=debug msg="Authentication failed" middlewareName=traefik-example-auth@kubernetescrd middlewareType=BasicAuth

traefik-abcd-nd9tr traefik time="xxx" level=debug msg="Authentication failed" middlewareType=BasicAuth middlewareName=traefik-example-auth@kubernetescrd
```
and the result is, that it doesnt accept test / test as user / pass.

can someone please check and help me out?

thanks!
