### DISCUSSION TITLE
traefik redirect to https not working(?)

### DISCUSSION THREAD

**Discussion by thisIsLoading** [mysticaltech/terraform-hcloud-kube-hetzner#1133] [Q&A] [answered]
Hi,

i set up a cluster and its really a breeze so far. however, i am very, VERY new to the whole k8s thing, so please bear with me.

in the kube.tf file there is this setting:

```
  # By default traefik is configured to redirect http traffic to https, you can set this to "false" to disable the redirection.
  # The default is true.
  # traefik_redirect_to_https = false
```

is this supposed to redirect all "virtual hosts" to https? if yes, then i might do it wrong but for some reason it does not do that for me. i have to admit that i had this disabled for convenience reasons until i had cert-manager working (dont worry, its just a play cluster, nothing in production) and after i enabled it again, the traefik dashboard as well as some other frontend deployment i have set up redirects just fine. However, i also created an ingress for the longhorn ui as well as signoz and those do not redirect to https.

this is the frontend ingress that redirects:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-frontend-ingress
  namespace: example
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: example-example-auth@kubernetescrd
spec:
  rules:
    - host: staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-frontend-service
                port:
                  number: 3000
  tls:
    - hosts:
        - staging.example.com
      secretName: staging-example-com-tls
```

and thats the longhorn ui ingress that doesnt:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.className: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-example-auth@kubernetescrd

spec:
  rules:
    - host: longhorn-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
  tls:
    - secretName: longhorn-tls
      hosts:
        - longhorn-staging.example.com
```

to my untrained eye it is not immediately obvious what i do wrong.

appreciating a little heads up. or is there a bug in the application of this redirect setting?

thanks!
