### DISCUSSION TITLE
PostgreSQL and proxy protocol of hetzner load balancer.

### DISCUSSION THREAD

**Discussion by vaceslav** [mysticaltech/terraform-hcloud-kube-hetzner#1323] [Q&A]
Hello,

I'm in the process of installing PostgreSQL using the [cloudnative-pg](https://cloudnative-pg.io/) operator, which has been quite straightforward and trouble-free.

Now, I'm looking to expose PostgreSQL port 5432 to the public internet. Although I understand the risks associated with port exposure, in my scenario, it's a development system and PostgreSQL needs to be accessible.

To accomplish this, I need to open TCP port 5432 in the Ingress controller. This can be achieved seamlessly by defining custom nginx-values, as shown below:

```yaml
nginx_values = <<EOT
controller:
  watchIngressWithoutClass: "true"
  kind: "Deployment"
  replicaCount: 1
  config:
    "use-forwarded-headers": "true"
    "compute-full-forwarded-for": "true"
    "use-proxy-protocol": "true"
  service:
    annotations:
      "load-balancer.hetzner.cloud/name": "k3s-nginx"
      "load-balancer.hetzner.cloud/use-private-ip": "true"
      "load-balancer.hetzner.cloud/disable-private-ingress": "true"
      "load-balancer.hetzner.cloud/location": "fsn1"
      "load-balancer.hetzner.cloud/type": "lb11"
      "load-balancer.hetzner.cloud/uses-proxyprotocol": "true"
      "load-balancer.hetzner.cloud/algorithm-type": "round_robin"
      "load-balancer.hetzner.cloud/health-check-interval": "15s"
      "load-balancer.hetzner.cloud/health-check-timeout": "10s"
      "load-balancer.hetzner.cloud/health-check-retries": "3"
      "load-balancer.hetzner.cloud/hostname": "example.com"
tcp:
  5432: "default/cluster-example-rw:5432"
EOT
```

Upon applying these settings, a new port definition is added to the nginx-ingress controller, along with a corresponding service definition in the Hetzner load balancer.

However, a challenge arises because all three service definitions (for http, https, and 5432) in the load balancer have the "use proxyprotocol" flag enabled due to the line:

`"load-balancer.hetzner.cloud/uses-proxyprotocol": "true"`

Since PostgreSQL doesn't support the proxy protocol, it needs to be disabled specifically for the load balancer service on port 5432.

My question is: Is it possible to configure "load-balancer.hetzner.cloud/uses-proxyprotocol": "true/false" per load-balancer service?

Thanks
