### DISCUSSION TITLE
System upgrade now allows setting an upgrade window if we can patch the manifest

### DISCUSSION THREAD

**Discussion by maggie44** [mysticaltech/terraform-hcloud-kube-hetzner#1591] [Ideas]
System upgrade now allows setting an upgrade window:

https://github.com/rancher/system-upgrade-controller/issues/63

Is there a way to patch the system upgrade manifest to include the required schedule?

```
spec:
  window:
    days:
      - "saturday"
      - "sunday"
    startTime: "8:00"
    endTime: "16:00"
    timeZone: "UTC"
```
