### DISCUSSION TITLE
Is it possible do downgrade k3s?

### DISCUSSION THREAD

**Discussion by loxy** [mysticaltech/terraform-hcloud-kube-hetzner#381] [Q&A] [answered]
I saw already discussion https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/376 and postet a comment there. But my question goes a little bit beyond, so I started a new thread.

I have a related issue (with same error log) because I have problems with [postgres operator](https://github.com/CrunchyData/postgres-operator) (PGO). It is not compatible with 1.25...

Is it possible to downgrade to version 1.24 without any problems? 

> So, that means that once [v1.25.3+k3s1](https://github.com/k3s-io/k3s/releases/tag/v1.25.3%2Bk3s1) was out, my cluster automatically switched to that Kubernetes version (while specifying stable)?
> 
> And if I set initial_k3s_channel = "v1.24" and apply again it will be reverted? With no drawbacks?

**Comment by otavio** [comment, marked as answer]
Considering we'd like to upgrade to *v1.24* releases, we can do this using following file:

```yaml
# kubectl apply -f ./k3s-upgrade.yaml
# Doc: https://rancher.com/docs/k3s/latest/en/upgrades/automated/
# agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s_upgrade: agent
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.24
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - {key: k3s_upgrade, operator: Exists}
      - {key: k3s_upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: node-role.kubernetes.io/control-plane, operator: NotIn, values: ["true"]}
  tolerations:
    - {key: server-usage, effect: NoSchedule, operator: Equal, value: storage}
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
  upgrade:
    image: rancher/k3s-upgrade
---
# server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s_upgrade: server
spec:
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.24
  serviceAccountName: system-upgrade
  nodeSelector:
    matchExpressions:
      - {key: k3s_upgrade, operator: Exists}
      - {key: k3s_upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: node-role.kubernetes.io/control-plane, operator: In, values: ["true"]}
  tolerations:
    - {key: node-role.kubernetes.io/control-plane, effect: NoSchedule, operator: Exists}
    - {key: CriticalAddonsOnly, effect: NoExecute, operator: Exists}
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
```
