### DISCUSSION TITLE
How to separate installation of CRDs and using them in kustomization.yaml?

### DISCUSSION THREAD

**Discussion by fkuersch** [mysticaltech/terraform-hcloud-kube-hetzner#427] [Q&A] [answered]
I'm trying to install & configure ArgoCD in customize.yaml.tpl

Unfortunately, when kustomize applies the ArgoCD application config, the CRDs are not available yet.

kustomization.yaml.tpl:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
namespace: argocd

resources:
- argocd-namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.2/manifests/ha/install.yaml
- argocd-applications.yaml
```

The first `terraform apply` fails with the following error:
```
error: resource mapping not found for name: "applications" namespace: "argocd" from "/var/user_kustomize/": no matches for kind "Application" in version "argoproj.io/v1alpha1"
ensure CRDs are installed first
```

When running `terraform apply` a second time, the `argocd-applications.yaml` will be applied correctly.

The current workaround appears to be installing the CRDs first, waiting for it to be established and then applying the config in a second step like this (for sealded-secrets):
```
kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.13.1/controller.yaml
kubectl wait --for condition=established crd sealedsecrets.bitnami.com
kustomize build . | kubectl apply -f -
```
Source: https://github.com/kubernetes-sigs/kustomize/issues/3502#issuecomment-849217820

How do I do this in terraform-hcloud-kube-hetzner?
