### DISCUSSION TITLE
Volume Encryption

### DISCUSSION THREAD

**Discussion by mysticaltech** [mysticaltech/terraform-hcloud-kube-hetzner#448] [Q&A] [answered]
### Discussed in https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/287

<div type='discussions-op-text'>

<sup>Originally posted by **JustinGuese** August 29, 2022</sup>
do we have an idea of how to implement volume encryption?
any ideas how we could solve it?</div>

**Comment by mysticaltech** [comment]
@JustinGuese, I will address this ASAP.

**Comment by mysticaltech** [comment]
@JustinGuese We very recently added support for Longhorn volumes and a custom values.yaml file to be added, please see the [kube.tf.example](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/master/kube.tf.example). 

And this is the [how](https://github.com/longhorn/longhorn/issues/1859#issuecomment-900759320) to add encryption, which is probably already possible now that you have complete flexibility over Longhorn's config. 

Please try it, and let me know if all is good so we can close this!

**Comment by mysticaltech** [comment]
I will consider this resolved, but if you tried and it turned out not possible because we are missing something, just let me know, and we will reopen this.

**Comment by JustinGuese** [comment]
@mysticaltech did you have a thought about making this feature donatable?

also: I'm currently stuck at that the nodes need some libraries installed for longhorn and the encryption to work...
How can I do that? does it even work for an existing installation?

` iscsiadm/open-iscsi`
`cryptsetup`
and the `dm_crypt` has to be loaded

Thanks again for your help!

**Comment by mysticaltech** [comment]
@JustinGuese We basically just install Longhorn for you, but then up to you to configure it. 

However, please have a look at this guide by @ifeulner, it touches on a lot of good subjects about how to use Longhorn optimally: https://gist.github.com/ifeulner/d311b2868f6c00e649f33a72166c2e5b

To install additional packages, you can use the `extra_packages_to_install` variable which accepts an array of strings like so ["package1", "package2"...].

Then you to apply to terraform again and add an ideally creating new agent nodepools that will mirror your old nodepools. This will temporarily double the size of your cluster. But then you can decommission the old nodes draining them all and then changing their (old) nodepool count to 0 (don't delete them). This method is explained better in the readme.

However, before doing all of this, you better ssh into a node and try to install the above packages manually via `transactional-update pkg install` just to make sure that they have the same name. Note that MicroOS is a version of Tumbleweed, so when searching for a package on Google search for the name of the package followed by "OpenSUSE Tumbleweed" and that will give you the real name used. Confirming the presence of the package for Tumbleweed is probably enough.

**Comment by JustinGuese** [comment]
i don't want to be annoying, but maybe someone already did this?
i managed to install cryptsetup as stated by mysticaltech, and longhorn installs nicely and everything...
but it still seems to struggle (longhorn problem).

using the "default" longhorn volume everything works, but as soon as I create an encrypted storageclass as stated in their doc, it fails to mount that volume. it does not throw an error, and I think the issue is specific to microos, so I guess it must be some permission error, or a missing library in microos? anyone experienced something similar?

**Comment by ifeulner** [comment]
Haven't used encrypted volumes yet, but currently the default install is lacking at least `cryptsetup`as @mysticaltech stated. I would suggest to check the server logs via `journalctl` and also longhorn logging...

**Reply by JustinGuese** [reply]
yeah I'm only getting "disk is not where it was expected to mount", so basically something in the mount part seems to go wrong... Possibly related to the read-only filesystem?

**Reply by mysticaltech** [reply]
@JustinGuese /var and /etc are read-write and we mount network volumes at `/var/longhorn`.

**Reply by JustinGuese** [reply]
alright, so no read only filesystem issue I guess

**Comment by JustinGuese** [comment, marked as answer]
Okay I got it to work, some findings from my journey:

## (preferred) hcloud csi encrypted volumes

The easiest way to get encrypted volumes working is actually to use the new encryption functionality of hcloud csi itself, see [https://github.com/hetznercloud/csi-driver](https://github.com/hetznercloud/csi-driver).
For this, you just need to create a secret containing the encryption key
```
   apiVersion: v1
   kind: Secret
   metadata:
     name: encryption-secret
     namespace: kube-system
   stringData:
     encryption-passphrase: foobar
```
and to create a new storage class
```
   apiVersion: storage.k8s.io/v1
   kind: StorageClass
   metadata:
     name: hcloud-volumes-encrypted
   provisioner: csi.hetzner.cloud
   reclaimPolicy: Delete
   volumeBindingMode: WaitForFirstConsumer
   allowVolumeExpansion: true
   parameters:
     csi.storage.k8s.io/node-publish-secret-name: encryption-secret
     csi.storage.k8s.io/node-publish-secret-namespace: kube-system
```
in addition, you nodes need to have the package `cryptsetup` installed, which can be done by adding the line `extra_packages_to_install = ["cryptsetup"]` to the [kube.tf](kube.tf) file.

If you want to check if the encryption really works (which I can confirm), you can mount the volume using the hetzner console, and then open it with `cryptsetup luksOpen /dev/sdb encryptedhetznervolume` (might be different to sdb), and then `mount /dev/mapper/encryptedhetznervolume /mnt`

## (not working) longhorn encryption

I tried this, but it did not work for me. For this, you need to install the `cryptsetup` package as well with the above command, or `transactional-update pkg install cryptsetup` in existing nodes, install longhorn, and create a new longhorn storage class and secret
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
stringData:
  CRYPTO_KEY_VALUE: "Your encryption passphrase"
  CRYPTO_KEY_PROVIDER: "secret"
```

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-encrypted-global
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "Delete" 
volumeBindingMode: Immediate 
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-crypto"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
```

there seems to be a problem though, as somehow this volume will not get mounted on the node. Anyways, the hetzner volume csi way is better anyways
