### DISCUSSION TITLE
Newbie question on load balancer

### DISCUSSION THREAD

**Discussion by Sampozzo** [mysticaltech/terraform-hcloud-kube-hetzner#694] [Q&A]
Hello, thank you for this great tool!
I'm studying those days kubernetes and found this great tool, but i'm a little confused about the load balancer, sorry if i ask a so simple question, i hope you can understand.

I'm running this really simple test.yaml, it works but it start a new load balancer only for it. By what i understand, i can use the already available LB, but i can't understand how.
Can you please help me?

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-namespace
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: test-lb
  name: test-lb
  namespace: test-namespace
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
```

Thank you very much and sorry!

**Comment by mysticaltech** [comment]
@Sampozzo You do not need to create a new LB service as you did above. Just use a ClusterIP service, and create an Ingress definition to point to it. That way it will use the LB that is already deployed and connected to your ingress controller, either nginx or traefik.

Btw, I highly recommend your ask chat.openai.com for help on this, it's extremely good at writing kubernetes manifest. But also read on Kubenetes Ingress definitions, and see some of the many great youtube videos on that.

**Comment by Sampozzo** [comment]
@mysticaltech thank you very much, and sorry again. 😊

**Reply by gefloh** [reply]
@Sampozzo Please continue to ask also the potentially simple questions. I am also pretty new to this and would appreciate it.

**Comment by Sampozzo** [comment]
Thanks @gefloh, I'm reading two kubernetes books, a lot of documentation online, i did some tests on my local network but now I'm stuck in a similar production env like this on hetzner with load balancer.
I have a lot to learn and will do, any real example to expose an nginx over 80 and 443 is very appreciated, chatgpt did't helped 😅

**Reply by mysticaltech** [reply]
@Sampozzo Here's an example in the examples folder https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/tree/master/examples/tls

**Comment by Sampozzo** [comment]
@mysticaltech yes thanks!!!
Finally i have it working thanks to the sample.
NB: i tested it pointing a cloudflare proxyed domain, and it doesn't need to deploy a certificate in the cluster, it is issued by cloudflare.
Really great!

Here is the complete example if anyone in the future need it.

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: test-namespace
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-namespace
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: test-namespace
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - my.test.domain
  rules:
    - host: my.test.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
```
