### DISCUSSION TITLE
Add instructions how to configure traefik

### DISCUSSION THREAD

**Discussion by aDingil** [mysticaltech/terraform-hcloud-kube-hetzner#704] [Q&A] [answered]
Hey @mysticaltech,

i´m currently want to add a middleware to traefik, but i´m not sure about the how.
My current tries destroy the given traefik config from terraform.

I can create prs to improve the examples/instructions after understanding the solution 😄 

Regards

**Comment by aDingil** [comment]
nvm about the middleware, solved it myself.
But how can i expose the traefik dashboard?

**Reply by mysticaltech** [reply]
@aDingil Try searching the traefik or k3s repo themselves, or even ask GPT-4. I wish I knew, but it's probably super simple.

**Reply by aDingil** [reply]
Hey,

thx for your quick response and sry for my delay....
So i ask GPT 3.x/4, visited the k3s docs and other things, but still no success.
I wasn´t able to port forward to my localhost or expose the dashboard to a hostname.

Some observations:
- traefik is not running in the namespace `kube-system`, it is running in the `traefik` namespace
- [this](https://k3s.rocks/traefik-dashboard/) is the only recent guide i was able find
- There a numerous [issues](https://github.com/k3s-io/k3s/issues?q=dashboard) about this topic in the k3s project

It is super weird, that this simple task is so obfuscated without any "official" docs from k3s.
Also for people who using helm there is the concept about [helmchartconfig](https://docs.k3s.io/helm#customizing-packaged-components-with-helmchartconfig) to modify packaged components like traefik

I just hope that i wouldn´t be dependent on the traefik dashboard to solve/debug a problem in the future.

Regards

**Reply by aDingil** [reply]
I don´t how and why, but now it does work:

List of changes:
- Created ingress and service yamls, described [here](https://k3s.rocks/traefik-dashboard/), but changed the namespace to `traefik`
- Created a helm config
```yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: traefik
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      traefik:
        expose: true
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
```
- Created a ingressroute for traefik
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: traefik
  generation: 8
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`HOST_URL`)
    services:
    - kind: TraefikService
      name: api@internal
```

Eventlog
![image](https://user-images.githubusercontent.com/101704040/231089246-e9898eee-0305-44dd-b8e4-015f4370c3bd.png)

Podlist
![image](https://user-images.githubusercontent.com/101704040/231089416-65003755-bd95-4fe9-89e2-58d7e769bb1f.png)


I also tried to reverted all those changes, to see when it stops the dashboard exposing, but it is still running and i still don´t how to stop or modify it
