### DISCUSSION TITLE
Longhorn unable to schedule replica

### DISCUSSION THREAD

**Discussion by MrHDOLEK** [mysticaltech/terraform-hcloud-kube-hetzner#713] [Q&A]
Hi guys, I have a problem with volume creation for the Longhorn. Volume is created and connected to the storage, but when connecting it to the pod, there is a problem.I use the default storage class in the longhorn if I try modify it then gets forbiten modified etc.  
Longhorn I made according to: https://gist.github.com/ifeulner/d311b2868f6c00e649f33a72166c2e5b
I checked the discussions of other people who had this problem and their solutions but it didn't help.
TF config
```
  agent_nodepools = [
    {
      name        = "agent-large",
      server_type = "cx31",
      location    = "nbg1",
      labels      = [
        "node.kubernetes.io/server-usage=tsdb",
        "node.kubernetes.io/storage-type=longhorn",
        "node.kubernetes.io/longhorn_volume_size=500"
      ],
      taints      = [],
      count       = 1
      longhorn_volume_size = 500
    },
    {
      name        = "egress",
      server_type = "cpx21",
      location    = "fsn1",
      labels      = [
        "node.kubernetes.io/server-usage=general",
        "node.kubernetes.io/storage-type=longhorn",
        "node.kubernetes.io/longhorn_volume_size=0",
        "node.longhorn.io/create-default-disk=config",
        "node.kubernetes.io/role=egress"
      ],
      taints = [
        "node.kubernetes.io/role=egress:NoSchedule"
      ],
      floating_ip = true
      count       = 1,
      longhorn_volume_size = 0
    }
```
k3s config
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
```
