### DISCUSSION TITLE
Another example of use and help needed (wordpress + mysql + longhorn pvc)

### DISCUSSION THREAD

**Discussion by Sampozzo** [mysticaltech/terraform-hcloud-kube-hetzner#720] [Q&A]
Hello, again! I'm here to show my progress and ask your help for my daily learning kubernetes.

As said in my previous post, i'm learning kubernetes and i found this tool as a great help creating and destroying clusters at <50cents/day, and maybe i will go in production with my services one day with it!! Thank you very much for it!

But readying a lot of documentation around the web, it is difficult for me to put them togheter in a real world working example. I like to understand what i'm doing. I don't want to use helm charts by now, maybe later.

I'm writing here because i don't know where to ask, and maybe my posts can be used by other user in my same situation... Please let me know if i'm doing wrong and i will stop this!

So the problem: i want to do a simple wordpress installation with persistent volumes over longhorn. All seems that is created and working. i've also installed an external rancher and i can see all the pods, deployments, volumes in the longhorn dashboard too. 

I'm pointing a proxyed cloudflare domain to the loadbalancer (no need to manage certificates, this is done by cloudflare) but i have 50% of 502 bad gateway refreshing the page in the browser. One time it works, one time i have 502.

What wrong with this config file i did by hands?

Thank you again!

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-ns
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wordpress-ns
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: wordpress-ns
  labels:
    app: wordpress
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress-ns
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpwd
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpressdb
        - name: MYSQL_PASSWORD
          value: MypwdSQL
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: wordpress-ns
  labels:
    app: wordpress
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-ns
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_USER
          value: wordpressdb
        - name: WORDPRESS_DB_PASSWORD
          value: MypwdSQL
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_PREFIX
          value: wp_
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: wordpress-ns
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
spec:
  tls:
    - hosts:
        - mydomain.com
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80
```
