### DISCUSSION TITLE
Updates to automatically installed workloads

### DISCUSSION THREAD

**Discussion by rombert** [mysticaltech/terraform-hcloud-kube-hetzner#945] [Q&A]
Hi,

I started looking into this project and looks like a perfect fit for my needs :-)

I like managing various non-core Kubernetes workloads via GitOps with [Flux 2](https://github.com/fluxcd/flux2) so I cut down on some of the add-ons so I can manage them myself:

```
  enable_cert_manager = false
  enable_metrics_server = false
  ingress_controller = "none"
```

There are still a couple of workloads which I view as either core ( e.g. coredns ) or Hetzner-specific so I'm leaving them managed by kube-hetzner:

- deploy/coredns
- deploy/hcloud-cloud-controller-manager
- deploy/hcloud-csi-controller
- deploy/system-upgrade-controller
- daemonset/hcloud-csi-node
- daemonset/kured

What is not clear to me is how these workloads get upgraded to the latest version, can anyone please clarify that?

**Comment by mysticaltech** [comment]
@rombert That is a great question that we perhaps did not answer clearly enough in the readme. Basically, when you deploy your cluster, a kustomization backup file gets created locally, and you can use that to update the above components. You also have other components that you need to update via helm, you can see them by looking at the rancher helm CRDs, just grep the `kubectl get crds` for helm.

**Reply by mysticaltech** [reply]
Also, PRs most welcome to improve this system.

**Reply by rombert** [reply]
Thanks for the reply @mysticaltech . I see something like this in my current directory

```yaml
"apiVersion": "kustomize.config.k8s.io/v1beta1"
"kind": "Kustomization"
"patchesStrategicMerge":
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: system-upgrade-controller
    namespace: system-upgrade
  spec:
    template:
      spec:
        containers:
          - name: system-upgrade-controller
            volumeMounts:
              - name: ca-certificates
                mountPath: /var/lib/ca-certificates
        volumes:
          - name: ca-certificates
            hostPath:
              path: /var/lib/ca-certificates
              type: Directory
- "kured.yaml"
- "ccm.yaml"
"resources":
- "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.17.2/ccm-networks.yaml"
- "https://github.com/kubereboot/kured/releases/download/1.14.0/kured-1.14.0-dockerhub.yaml"
- "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
- "hcloud-csi.yml"
```

So at least I can figure out the release version of CCM and Kured and where they were installed from. What I am still missing is the CSI part, that one references a local file named "hcloud-csi.yml" but I can't find it anywhere. Do you have any suggestion regarding that?
