### DISCUSSION TITLE
Problems using smb

### DISCUSSION THREAD

**Discussion by Semptic** [mysticaltech/terraform-hcloud-kube-hetzner#951] [Q&A]
I try to use hetzner storage box for storing some data. This only works without the usage of `subDir` like so:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-box
provisioner: smb.csi.k8s.io
parameters:
  source: "//<user>.your-storagebox.de/backup"
  csi.storage.k8s.io/node-stage-secret-name: "storage-box-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Delete  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - vers=3.0
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
```

Although when I use explicit or implicit `subDir` it doesn't:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-box
provisioner: smb.csi.k8s.io
parameters:
  source: "//<user>.your-storagebox.de/backup"
  subDir: "${pvc.metadata.namespace}-${pvc.metadata.name}" 
  csi.storage.k8s.io/node-stage-secret-name: "storage-box-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Delete  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - vers=3.0
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
```

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-box
provisioner: smb.csi.k8s.io
parameters:
  source: "//<user>.your-storagebox.de/backup"
  # if csi.storage.k8s.io/provisioner-secret is provided, will create a sub directory
  # with PV name under source
  csi.storage.k8s.io/provisioner-secret-name: "storage-box-credentials"
  csi.storage.k8s.io/provisioner-secret-namespace: "default"
  csi.storage.k8s.io/node-stage-secret-name: "storage-box-credentials"
  csi.storage.k8s.io/node-stage-secret-namespace: "default"
reclaimPolicy: Delete  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - vers=3.0
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
```

With either of those last two configs I'm getting an error like
```
rpc error: code = Internal desc = failed to mount smb server: rpc error: code = Internal desc = MkdirAll /tmp/pvc-001f3e32-12c1-4e62-bb9d-f61b928040c8 failed with error: mkdir /tmp/pvc-001f3e32-12c1-4e62-bb9d-f61b928040c8: read-only file system
```

Does anyone have an idea how I can solve this? I could do it with `subPath` on the container, but I would prefer if the pv would do this.
