### DISCUSSION TITLE
Storage Class for node local storage

### DISCUSSION THREAD

**Discussion by HendrikLevering** [mysticaltech/terraform-hcloud-kube-hetzner#957] [Q&A] [answered]
First of all, thanks for the great work.
I have a running cluster. I created it by an almost plain kube.tf file (adjusted node pools to cx11 and deleted express node pool). I created Postgres via the crunchy operator. That worked but it uses Hetzner cloud volumes. By default  crunchy uses the default storage class which hcloud-volumes. How can I create a storage class that uses hetzners node storage for volumes?

**Comment by transmogrifix** [comment, marked as answer]
You should use Longhorn, it will use NVME node storage if you use `longhorn_volume_size = 0`.
See https://gist.github.com/ifeulner/d311b2868f6c00e649f33a72166c2e5b for more info.

**Reply by HendrikLevering** [reply]
Thanks for your reply. I followed the gist, but I am still not able to get it working.
Longhorn is installed in kubernetes.
I have the following node-pool:
```    
{
      name        = "agent-small-postgres",
      server_type = "cax11",
      location    = "fsn1",
      labels = [
        "DBpostgres=NodeStorage"
      ],
      taints = [
        "DBpostgres=NodeStorage:NoSchedule"
      ],
      count       = 2
      longhorn_volume_size = 0

    }
```

And the following storage class:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast-pg
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
  diskSelector: "nvme"
```

If I tell the Postgres operator to use `longhorn-fast-pg` storage class, then I get this error `0/9 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/9 nodes are available:`

If I use the default hcloud storage class, then the pods are scheduled on the correct nodes.
Am I missing something?
