### DISCUSSION TITLE
How to correct configuration capabilities fo prometheus-node-exporter? maybe need add rules for seLinux?

### DISCUSSION THREAD

**Discussion by jidckii** [mysticaltech/terraform-hcloud-kube-hetzner#969] [Q&A]
Recently, I wondered why I do not have metrics for file systems in the cluster?

![image](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/6608896/11edff0c-e884-4704-8808-7983a3ed44c2)

It turned out that node-exporter did not have enough privileges + the exception rules needed to be corrected.

`node_scrape_collector_success{collector="filesystem"} 0`
in logs:
`err="open /host/proc/1/mounts: permission denied"`

I added `privileged: true` , but statistics for PVC did not appear, only for  rootfs.

```yaml
## promtheus-node-exporter sub-chart configurable values
## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
##
prometheus-node-exporter:
  tolerations:
    - key: ""
      operator: Exists
      effect: NoSchedule
    - key: ""
      operator: Exists
      effect: NoExecute
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 50Mi
  containerSecurityContext:
    allowPrivilegeEscalation: true
    privileged: true
    capabilities:
      add:
      - CAP_SYS_RESOURCE
      - CAP_SYS_ADMIN
  extraArgs:
    - --log.level=debug
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|boot|run/credentials/.+|run/k3s/containerd/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpds|tmpfs|shm|fuse.lxcfs)$

```

Error in in logs:

```log
ts=2023-09-07T09:46:38.109Z caller=filesystem_linux.go:96 level=debug collector=filesystem msg="Error on statfs() system call" rootfs=/host/root/var/lib/kubelet/pods/af246936-a625-4dd1-a64c-e07ce1876fef/volumes/kubernetes.io~csi/pvc-94e4c6a3-03ad-4ce9-9d9b-f955d591c4a5/mount err="permission denied"
```

```yaml
  containerSecurityContext:
    allowPrivilegeEscalation: true
    privileged: true
    runAsNonRoot: false
    runAsUser: 0
```

I had to run it as root, then the data showed up. But it doesn't seem very safe.
I'm not strong in seLinux policies, but it seems that the barrel can be in this?
